### ISSUE TITLE
Line variable scope show up as undefined and chest menu cannot open

### ISSUE THREAD

**Issue by HellishBro** [DFOnline/editor#29]
![image](https://github.com/DFOnline/editor/assets/84367421/adc41d25-45a3-4c0d-a3ab-73e6cd5e58fc)

and also pattern_element and also components renders as %pn_el% and %comp% in preview chest mode

**Comment by HellishBro** [comment]
![image](https://github.com/DFOnline/editor/assets/84367421/189a1575-a35a-47a2-a8be-3b3273d20166)

**Comment by GeorgeRNG** [comment]
https://github.com/DFOnline/editor/commit/19b177907c34c3dece23237991959a5d11e510e6
Has been pushed to the main site.
